### PR TITLE
Tautulli python 3 compat, glep 81 update, misc QA cleanups, drop fix-gnustack

### PR DESCRIPTION
**Pull request by xartin**
1) Major version update for tautulli to support eapi=7 + python 3 with proper openrc init and systemd service unit configs
2) moved default tautulli install dir to /var/lib
3) Added acct-group config files for tautulli and plex in case mgorny purges acct-user/plex and acct-group/plex from portage
4) updated several metadata.xml files mentioning current maintainer for consistency
5) fixed acct-user/* and acct-group/* versions existing in overlay to match portage versions for acct-*/package-0.ebuild 
6) I purged fix-gnustack from the repo fork by mistake however it exists in portage. One less ebuild to maintain here.
7) QA inherit cmake-utils -> cmake and RESTRICT ( network-sandbox ) was invalid for plex-media-player. cleanups were requested by repoman for plex-media-player.
8) Tested both systemd and openrc services for start/stop functionality.
9) figuring out the init configuration created several messy redundant commits but it works :)
9) Thanks for all you do maintaining plex-media server! Merry Christmas Comio enjoy the repo maintenance update.

### CODE REVIEW

**Comment by TheGreatMcPain** [comment]
Might be a good idea to expand on how to disable the `network-sandbox` feature
for those who might not know how since removing it from RESTRICT will trigger
an error.

Something like this after the `if use download && has network-sandbox $FEATURES; then` line.

```
eerror "You must disable 'network-sandbox' feature in order to use 'download' flag"
einfo
einfo "This can be done by doing the following"
einfo
einfo "# echo 'FEATURES="-network-sandbox"' >> /etc/portage/env/disable-network-sandbox"
einfo "# echo "media-tv/plex-medis-player disable-network-sandbox" >> /etc/portage/package.env/plex-media-player"
einfo && die
```

**Comment by xartin** [comment]
closing for further work

**Comment by comio** [comment]
Hi @xartin, can you propose again a refresh update for tautulli and plex-media-player? Thanks.

luigi

**Comment by xartin** [comment]
I closed this because tautuilli dropped python 2.7 support and pushing the ebuild became a priority and with the lack of response I could only assume you were engaged by more important things. 

After fighting with some of those commit tests for several hours due to silly reasons I also forgot to create the acct-user and acct-group packages correctly for tautulli. Since I don't do a lot of ebuild development frequently four ish hours every other week seems to be a good liit for more signficant projects such as major version bumps for tautulli but preparing this was a good day. 

I've pushed working tautulli ebuild with acct-user and acct-group packages to my usernet-overlay repo if your interested in upgrading tautulli.

I intended to get back to this asap but Canadian winter is not enjoyable. This tends to negatively affect my productivity with stay indoors or freeze to death -40 Celsius temperatures for three months. Hopefully I can get out of this country when covid is over. I was looking for work in Europe before october and had several interviews in france and germany and was considering looking online for work in Italy since i visited Liguria around October 2019. My family ancestry doesnt enjoy the cold weather and I had the misfortune of having to grow up on one of the two coldest contents on the planet lol.

This pull request really did need some additional work to become usable. Not a lot but perhaps another reivew on my behalf would have spotted the missing packages.

Unrelated issue but just curious. When are you goung to update the python targets hardcoded in the plex-media-server ebuild to drop python 2.7 or or that still no longer possible?

**Comment by comio** [comment]
Hi @xartin,

I wish the best for your professional and personal life. Can I ask you your professional interests?

Regarding plex-media-server, I just forgot the PYTHON_COMPACT variable, i will remove in the next round.
Instead, I will copy directly from your repository the tautulli ebuilds, if you agree. I'm not using tautulli any more and I cannot check if it works or not.

ciao

luigi

**Comment by xartin** [comment]
Thanks Luigi,

Residing in Canada due to old spinal physical injury in my younger years hasn't provided many sustainable bountiful opportunities. Information tech was supposed to be the answer but so many employers in my central canadian city have very limited use of or understanding of non commercial Linux Infrastructure that's common in central europe. Canadian geography being what it is travelling between major cities to seek out new opportunities is a very challenging obstacle when the next major city is typically 400+ kms away

Perhaps my interest has always been infrastructure management or engineering. I used to work for a managed services provider as the only on staff systems engineer in my local city but those opportunities are very uncommon in Canada unless you reside in Vancouver, Calgary, Toronto Ottawa or Montreal and none of those options are any warmer or more hospitable during winter months besides Vancouver. The cost of living in vancouver largely eliminates living in vancouver within range of rapid transit as reasonable.

Visiting several friends across europe was eye opening and revealing of how much social pressure is exerted upon residents of my central canadian city to just eat crow and live here until your old rotten or dead whichever comes first.

Regarding the python_compat variable for plex-media-server it's best if that config variable is updated when the ebuild is ready to drop python 2.7 support to reflect `PYTHON_COMPAT=( python3_{6,7,8,9} )`

Regarding my ebuilds your most welcome to use or redistribute them as you see fit :)

**Comment by comio** [comment]
I copied directly the files

**Pull request closed without merging**
